version: 2
executorType: docker
jobs:
  build-app:
    resource_class: medium
    environment:
      - GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      - REACT_NATIVE_MAX_WORKERS: 2
      - ANDROID_BUILD_TOOLS_VERSION: '28.0.3'
    working_directory: ~/app
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Lint
          command: yarn lint
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "example/android/gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "example/android/build.gradle" }}
      - run:
          name: Reuse Gradle wrapper from example
          command: |
            cp -a example/android/{gradle,gradlew,gradlew.bat} android/
      - run:
          name: Run Checks
          command: |
            cd android/
            ./gradlew check
      - store_artifacts:
          path: android/build/reports/
      - run:
          name: Install dependencies of the example app
          command: cd example/ && yarn --frozen-lockfile --non-interactive
      - run:
          name: Check for errors in the example app using Flow
          command: |
            cd example/ && yarn flow
      - run:
          name: Build Sample App
          command: |
            cd example/android && chmod +x ./gradlew && ./gradlew build
      - store_artifacts:
          path: example/android/app/build/reports
          destination: app
      - save_cache:
          key: v1-gradle-wrapper-{{ checksum "example/android/gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper/
      - save_cache:
          key: v1-gradle-cache-{{ checksum "example/android/build.gradle" }}
          paths:
            - ~/.gradle/caches/
workflows:
  version: 2
  build-and-lint-app:
    jobs:
      - build-app
